// AUTOGENERATED FILE
// This file was generated from grammar.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface ArithmeticActionDict<T> extends BaseActionDict<T> {
  Exp?: (this: NonterminalNode, arg0: IterationNode) => T;
  Block?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: NonterminalNode, arg3: IterationNode) => T;
  ident?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
  ws?: (this: NonterminalNode, arg0: TerminalNode) => T;
  nl?: (this: NonterminalNode, arg0: TerminalNode) => T;
  indent?: (this: NonterminalNode, arg0: IterationNode) => T;
  text?: (this: NonterminalNode, arg0: IterationNode, arg1: NonterminalNode) => T;
  choice?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: IterationNode) => T;
}

export interface ArithmeticSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: ArithmeticActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: ArithmeticActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: ArithmeticActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: ArithmeticActionDict<T>): this;
}

export interface ArithmeticGrammar extends Grammar {
  createSemantics(): ArithmeticSemantics;
  extendSemantics(superSemantics: ArithmeticSemantics): ArithmeticSemantics;
}

declare const grammar: ArithmeticGrammar;
export default grammar;

