// AUTOGENERATED FILE
// This file was generated from grammar.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface TerminalActionDict<T> extends BaseActionDict<T> {
  line?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  commentLine?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: IterationNode) => T;
  blockLine?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: IterationNode, arg3: NonterminalNode, arg4: IterationNode, arg5: NonterminalNode) => T;
  choiceLine?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: IterationNode, arg3: NonterminalNode, arg4: IterationNode, arg5: NonterminalNode) => T;
  divertLine?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  textLine?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  tagLine?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
  blankLine?: (this: NonterminalNode, arg0: IterationNode) => T;
  divert?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: NonterminalNode, arg3: IterationNode) => T;
  body?: (this: NonterminalNode, arg0: IterationNode) => T;
  segment?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  interp?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: NonterminalNode, arg3: IterationNode, arg4: TerminalNode) => T;
  chunk?: (this: NonterminalNode, arg0: IterationNode) => T;
  escape?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  escapable?: (this: NonterminalNode, arg0: TerminalNode) => T;
  tags?: (this: NonterminalNode, arg0: IterationNode) => T;
  tag?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: IterationNode, arg3: IterationNode) => T;
  tagArg?: (this: NonterminalNode, arg0: IterationNode, arg1: NonterminalNode) => T;
  argToken?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  quotedArg?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: TerminalNode) => T;
  bareArg?: (this: NonterminalNode, arg0: IterationNode) => T;
  ident?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode, arg1: IterationNode) => T;
  indent?: (this: NonterminalNode, arg0: IterationNode) => T;
  hs?: (this: NonterminalNode, arg0: TerminalNode) => T;
  Expr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  OrExpr_or?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  OrExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  AndExpr_and?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  AndExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  NotExpr_not?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  NotExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  CompExpr_compare?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  CompExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  AddExpr_add?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  AddExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  MulExpr_mul?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  MulExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Unary_negate?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  Unary?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Primary_paren?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  Primary?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  compOp?: (this: NonterminalNode, arg0: TerminalNode) => T;
  addOp?: (this: NonterminalNode, arg0: TerminalNode) => T;
  mulOp?: (this: NonterminalNode, arg0: TerminalNode) => T;
  number?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode, arg2: IterationNode) => T;
  string?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: TerminalNode) => T;
  boolean?: (this: NonterminalNode, arg0: TerminalNode) => T;
  varRef?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  keyword?: (this: NonterminalNode, arg0: TerminalNode) => T;
}

export interface TerminalSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: TerminalActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: TerminalActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: TerminalActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: TerminalActionDict<T>): this;
}

export interface TerminalGrammar extends Grammar {
  createSemantics(): TerminalSemantics;
  extendSemantics(superSemantics: TerminalSemantics): TerminalSemantics;
}

declare const grammar: TerminalGrammar;
export default grammar;

